# Generated by Django 3.2.8 on 2022-07-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='frontImageURL',
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='frontImageFile',
            field=models.ImageField(blank=True, null=True, upload_to='frontImages'),
        ),
    ]
