# Generated by Django 3.2.8 on 2022-07-22 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_blogmodel_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('message', models.TextField()),
                ('BlogSlug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blogmodel')),
            ],
        ),
    ]
