# Generated by Django 3.2.8 on 2023-02-26 16:01

from django.db import migrations, models
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_commentmodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='frontImageFileAlt',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='frontImageFile',
            field=django_resized.forms.ResizedImageField(crop=None, default=django.utils.timezone.now, force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[1920, 1080], upload_to='frontImages'),
            preserve_default=False,
        ),
    ]
