# Generated by Django 3.2.8 on 2023-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20230226_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='frontImageFileAlt',
            field=models.CharField(max_length=150),
        ),
    ]
